FIX - dropdown de Tipos de espaço agora aparecem em ordem alfabética
RedeMapas/mapas pull request #304
Opened 2024-07-15 17:54 UTC by LeonardoZanotti

## Descrição

Insere função usort dentro da função getRegisteredEntityTypes no arquivo app.php para ordenar as entidades por ordem alfabética baseado na propriedade "name" do objeto.

![Screenshot from 2024-07-15 14-47-33](https://github.com/user-attachments/assets/4a34cc79-5cc3-4d49-8f01-f1a4c51e0d4b)

## Validação

![名称未設定](https://github.com/user-attachments/assets/ed99f3f9-2963-444d-b308-680ed4a3c60b)

## Issues relacionadas

[ESPAÇOS] Dropdown de "Tipo de espaço" não está em ordem alfabética #101

2024-07-23 13:04 UTC, lpirola commented
@Spirou1 poderia revisar, por favor?

2024-07-25 13:45 UTC, Spirou1 approved these changes
Testei aqui e está funcionando normalmente

2024-08-02 16:57 UTC, lpirola requested changes
@LeonardoZanotti precisa revisar o código para não incluir alterações que não foram as que você realizou.

2024-08-15 22:10 UTC, LeonardoZanotti commented
alterações desnecessárias removidas

2024-08-28 18:35 UTC, merged